try...catch...finally
```
try {

} catch (Exception $exception) {

} finally {

}
```

建立可拋出例外的函數
```
function validPassword($password){
	if(trim($password)=='') throw new Exception('密碼為空字串');
	if(strlen($password)<6) throw new Exception('密碼長度太短');
	if(is_numeric($password)) throw new Exception('密碼需包含字符');
	return true;
}
```

在try區塊觸發例外，catch區塊捕捉例外
```
try{
	validPassword('12345');
}catch(Exception $e){
	echo $e->getMessage();
	exit;
}
```

開啟檔案的例外處理
```
$DOCUMENT_ROOT=$_SERVER['DOCUMENT_ROOT'];
@$fp=fopen("$DOCUMENT_ROOT/log.txt",'rb');
try{
	if(!$fp) throw new Exception('找不到檔案或檔案路徑有誤');
}catch(Exception $e){
	echo $e->getMessage();
	echo '在檔案'.$e->getFile().'的'.$e->getLine().'行';
}
@fclose($fp);
```